Fitting and Fitting Types

- Underfitting
- Overfitting
- Balancedfitting

In [1]:
import seaborn as sns
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("diamonds.csv")

In [3]:
df.head(3)

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31

In [4]:
df = pd.get_dummies(df,columns=["cut","color","clarity"],drop_first=True, dtype=int)

In [5]:
df

,Unnamed: 0,carat,depth,table,price,x,y,z,cut_Good,cut_Ideal,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,1,0.23,61.5,55.0,326,3.95,3.98,2.43,0,1,...,0,0,0,0,0,1,0,0,0,0
1,2,0.21,59.8,61.0,326,3.89,3.84,2.31,0,0,...,0,0,0,0,1,0,0,0,0,0
2,3,0.23,56.9,65.0,327,4.05,4.07,2.31,1,0,...,0,0,0,0,0,0,1,0,0,0
3,4,0.29,62.4,58.0,334,4.20,4.23,2.63,0,0,...,0,1,0,0,0,0,0,1,0,0
4,5,0.31,63.3,58.0,335,4.34,4.35,2.75,1,0,...,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,60.8,57.0,2757,5.75,5.76,3.50,0,1,...,0,0,0,0,1,0,0,0,0,0
53936,53937,0.72,63.1,55.0,2757,5.69,5.75,3.61,1,0,...,0,0,0,0,1,0,0,0,0,0
53937,53938,0.70,62.8,60.0,2757,5.66,5.68,3.56,0,0,...,0,0,0,0,1,0,0,0,0,0
53938,53939,0.86,61.0,58.0,2757,6.15,6.12,3.74,0,0,...,1,0,0,0,0,1,0,0,0,0
53939,53940,0.75,62.2,55.0,2757,5.83,5.87,3.64,0,1,...,0,0,0,0,0,1,0,0,0,0

In [6]:
df = df.drop('Unnamed: 0', axis=1)

In [7]:
df

,carat,depth,table,price,x,y,z,cut_Good,cut_Ideal,cut_Premium,...,color_H,color_I,color_J,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.23,61.5,55.0,326,3.95,3.98,2.43,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,0.21,59.8,61.0,326,3.89,3.84,2.31,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,0.23,56.9,65.0,327,4.05,4.07,2.31,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0.29,62.4,58.0,334,4.20,4.23,2.63,0,0,1,...,0,1,0,0,0,0,0,1,0,0
4,0.31,63.3,58.0,335,4.34,4.35,2.75,1,0,0,...,0,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,60.8,57.0,2757,5.75,5.76,3.50,0,1,0,...,0,0,0,0,1,0,0,0,0,0
53936,0.72,63.1,55.0,2757,5.69,5.75,3.61,1,0,0,...,0,0,0,0,1,0,0,0,0,0
53937,0.70,62.8,60.0,2757,5.66,5.68,3.56,0,0,0,...,0,0,0,0,1,0,0,0,0,0
53938,0.86,61.0,58.0,2757,6.15,6.12,3.74,0,0,1,...,1,0,0,0,0,1,0,0,0,0
53939,0.75,62.2,55.0,2757,5.83,5.87,3.64,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [8]:
y = df["price"]
x = df.drop("price",axis=1)

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=19,train_size=0.76)

In [10]:
lm = LinearRegression()
model = lm.fit(x_train,y_train)

In [11]:
model.score(x_test,y_test)

0.9200645244634401

In [12]:
model.score(x_train,y_train)

0.9196844286376016

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   carat          53940 non-null  float64
 1   depth          53940 non-null  float64
 2   table          53940 non-null  float64
 3   price          53940 non-null  int64
 4   x              53940 non-null  float64
 5   y              53940 non-null  float64
 6   z              53940 non-null  float64
 7   cut_Good       53940 non-null  int64
 8   cut_Ideal      53940 non-null  int64
 9   cut_Premium    53940 non-null  int64
 10  cut_Very Good  53940 non-null  int64
 11  color_E        53940 non-null  int64
 12  color_F        53940 non-null  int64
 13  color_G        53940 non-null  int64
 14  color_H        53940 non-null  int64
 15  color_I        53940 non-null  int64
 16  color_J        53940 non-null  int64
 17  clarity_IF     53940 non-null  int64
 18  clarity_SI1    53940 non-null  int64
 19  clarity_SI2    53940 non-null  int64
 20  clarity_VS1    53940 non-null  int64
 21  clarity_VS2    53940 non-null  int64
 22  clarity_VVS1   53940 non-null  int64
 23  clarity_VVS2   53940 non-null  int64
dtypes: float64(6), int64(18)
memory usage: 9.9 MB